
package com.tests.jaxws.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DiscsServiceImplService", targetNamespace = "http://ws.jaxws.tests.com/", wsdlLocation = "http://localhost:9999/ws/discs")
public class DiscsServiceImplService
    extends Service
{

    private final static URL DISCSSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException DISCSSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName DISCSSERVICEIMPLSERVICE_QNAME = new QName("http://ws.jaxws.tests.com/", "DiscsServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9999/ws/discs");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DISCSSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        DISCSSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public DiscsServiceImplService() {
        super(__getWsdlLocation(), DISCSSERVICEIMPLSERVICE_QNAME);
    }

    public DiscsServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DISCSSERVICEIMPLSERVICE_QNAME, features);
    }

    public DiscsServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, DISCSSERVICEIMPLSERVICE_QNAME);
    }

    public DiscsServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DISCSSERVICEIMPLSERVICE_QNAME, features);
    }

    public DiscsServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DiscsServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DiscsService
     */
    @WebEndpoint(name = "DiscsServiceImplPort")
    public DiscsService getDiscsServiceImplPort() {
        return super.getPort(new QName("http://ws.jaxws.tests.com/", "DiscsServiceImplPort"), DiscsService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DiscsService
     */
    @WebEndpoint(name = "DiscsServiceImplPort")
    public DiscsService getDiscsServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.jaxws.tests.com/", "DiscsServiceImplPort"), DiscsService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DISCSSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw DISCSSERVICEIMPLSERVICE_EXCEPTION;
        }
        return DISCSSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
