
package com.tests.jaxws.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DiscsService", targetNamespace = "http://ws.jaxws.tests.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DiscsService {


    /**
     * 
     * @return
     *     returns java.util.List<com.tests.jaxws.ws.Disc>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDiscsList", targetNamespace = "http://ws.jaxws.tests.com/", className = "com.tests.jaxws.ws.GetDiscsList")
    @ResponseWrapper(localName = "getDiscsListResponse", targetNamespace = "http://ws.jaxws.tests.com/", className = "com.tests.jaxws.ws.GetDiscsListResponse")
    public List<Disc> getDiscsList();

    /**
     * 
     * @param arg0
     * @return
     *     returns com.tests.jaxws.ws.Disc
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDiscsById", targetNamespace = "http://ws.jaxws.tests.com/", className = "com.tests.jaxws.ws.GetDiscsById")
    @ResponseWrapper(localName = "getDiscsByIdResponse", targetNamespace = "http://ws.jaxws.tests.com/", className = "com.tests.jaxws.ws.GetDiscsByIdResponse")
    public Disc getDiscsById(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addDisc", targetNamespace = "http://ws.jaxws.tests.com/", className = "com.tests.jaxws.ws.AddDisc")
    @ResponseWrapper(localName = "addDiscResponse", targetNamespace = "http://ws.jaxws.tests.com/", className = "com.tests.jaxws.ws.AddDiscResponse")
    public int addDisc(
        @WebParam(name = "arg0", targetNamespace = "")
        Disc arg0);

}
